import React from 'react'
import Health_trained from './health_trained';

function Footer() {

    const techList = ['Python', 'React.Js', 'Express.Js(Node.Js)', 'Flask', 'Tensorflow', 'Scikit-Learn', 'Keras', 'Spacy', 'Transfer-Learning (Bart Model)'];

    return (
        
        <div className='max-w-[1200px] mx-auto px-6 py-10'>
            <footer className='mt-15 pt-15 border-t border-slate-400 text-center'>
                <Health_trained/>
                <div>
                    <p className='text-2xl font-bold text-[#0da5a3] mb-2'>Tech Stack Used</p>
                    <p className='text-[12px] text-slate-500 uppercase tracking-widest mb-3'>Includes library used to train the model also</p>

                    <div className='flex flex-wrap items-center justify-center gap-3 text-center'>
                        {techList.length > 0 ?
                            (<>
                                {techList.map((tech, index) => (
                                    <span key={index} className='border border-[#0da5a3]/70 text-[#0da5a3] bg-[#0da5a3]/10 px-2 py-1 rounded-full'>{tech}</span>
                                ))}
                            </>) : (<></>)
                        }
                    </div>
                </div>
                <div className='max-w-3xl mx-auto mt-15 border border-slate-300 bg-slate-100 rounded-2xl justify-center px-6 py-6 mb-10'>
                    <p className='text-sm text-slate-700 font-bold tracking-wider mb-2 '>Legal Disclaimer</p>
                    <p className='text-sm text-slate-500'>AI Health Insight is a decision-support tool meant for use by licensed medical professionals. Predictions generated by AI models are probabilistic and should not be used as the sole basis for diagnosis. Always consult with a qualified physician. This software does not constitute medical advice.This project is done for gaining skills and to understand real world problems.The dataset used to train the models is legal. <span className='text-red-800'>Models may predict worng diseases.</span></p>
                </div>
                <p className="text-sm text-slate-400">
                    © 2026 <span className='text-[#0da5a3]'>Arogya</span>.<span className='text-[#0da5a3] font-bold'> SUVVADA THANUJ</span>
                </p>
            </footer >
        </div >
    )
}

export default Footer
